// frontend/src/components/layout/Navbar.svelte
<script lang="ts">
  import { user } from "$lib/stores/auth";
  import { sidebarOpen, theme } from "$lib/stores/ui";
  import { onMount } from "svelte";

  let currentUser: { email?: string } | null = null;

  onMount(() => {
    const unsub = user.subscribe((u) => (currentUser = u));
    return unsub;
  });

  function toggleSidebar() {
    sidebarOpen.update((v) => !v);
  }

  function toggleTheme() {
    theme.update((t) => (t === "light" ? "dark" : "light"));
  }
</script>

<header
  class="h-14 flex items-center justify-between px-4 md:px-6
         bg-surfaceLight dark:bg-surfaceDark
         border-b border-borderLight dark:border-borderDark
         transition-colors duration-300"
>
  <div class="flex items-center space-x-3">
    <button
      class="md:hidden p-2 rounded-md text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
      on:click={toggleSidebar}
      aria-label="Toggle menu"
    >
      ☰
    </button>
    <span class="text-lg font-semibold text-primaryDefault dark:text-primaryDark">
      CloudStore AI
    </span>
  </div>

  <div class="flex items-center space-x-4">
    <button
      on:click={toggleTheme}
      class="p-2 rounded-md hover:bg-gray-100 dark:hover:bg-gray-800 text-gray-600 dark:text-gray-300 transition-colors"
      aria-label="Toggle theme"
    >
      {#if $theme === "dark"} 🌙 {:else} ☀️ {/if}
    </button>

    {#if currentUser}
      <span class="hidden md:inline text-gray-700 dark:text-gray-200 text-sm">{currentUser.email}</span>
      <button
        class="px-3 py-1 text-sm bg-dangerLight dark:bg-dangerDark text-white rounded-md hover:opacity-90 transition"
        on:click={() => alert("TODO: logout")}
      >
        Logout
      </button>
    {:else}
      <a href="/auth/login" class="text-primaryDefault dark:text-primaryDark hover:underline text-sm">
        Login
      </a>
    {/if}
  </div>
</header>

// components/Navbar.tsx
import React from 'react';
import { Menu, Sun, Moon, LogOut, User } from 'lucide-react';
import { useTheme } from '../contexts/ThemeContext';
import { useAuth } from '../contexts/AuthContext';

interface NavbarProps {
  onMenuClick: () => void;
}

export const Navbar: React.FC<NavbarProps> = ({ onMenuClick }) => {
  const { theme, toggleTheme } = useTheme();
  const { user, logout } = useAuth();

  return (
    <header 
      className="sticky top-0 z-30 h-16 bg-[var(--surface)] border-b border-[var(--border)]"
      style={{ boxShadow: 'var(--shadow-sm)' }}
    >
      <div className="h-full px-4 lg:px-6 flex items-center justify-between">
        {/* Left side */}
        <div className="flex items-center gap-4">
          <button
            onClick={onMenuClick}
            className="lg:hidden p-2 hover:bg-[var(--background)] rounded-lg transition-colors"
          >
            <Menu className="w-5 h-5 text-[var(--text-secondary)]" />
          </button>
          
          <div className="hidden lg:flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-[#2563EB] to-[#1E40AF] flex items-center justify-center lg:hidden">
              <span className="text-white">☁️</span>
            </div>
            <h1 className="font-semibold text-[var(--text-primary)] hidden sm:block">
              CloudStore AI
            </h1>
          </div>
        </div>

        {/* Right side */}
        <div className="flex items-center gap-2">
          {/* Theme Toggle */}
          <button
            onClick={toggleTheme}
            className="p-2 hover:bg-[var(--background)] rounded-lg transition-colors"
            aria-label="Toggle theme"
          >
            {theme === 'light' ? (
              <Moon className="w-5 h-5 text-[var(--text-secondary)]" />
            ) : (
              <Sun className="w-5 h-5 text-[var(--text-secondary)]" />
            )}
          </button>

          {/* User Menu */}
          {user && (
            <>
              <div className="hidden sm:flex items-center gap-2 px-3 py-2 rounded-lg bg-[var(--background)]">
                <div className="w-8 h-8 rounded-full bg-gradient-to-br from-[#2563EB] to-[#1E40AF] flex items-center justify-center">
                  <User className="w-4 h-4 text-white" />
                </div>
                <div className="hidden md:block">
                  <p className="text-sm text-[var(--text-primary)]">{user.name}</p>
                  <p className="text-xs text-[var(--text-tertiary)]">{user.email}</p>
                </div>
              </div>

              <button
                onClick={logout}
                className="p-2 hover:bg-[var(--background)] rounded-lg transition-colors"
                aria-label="Logout"
              >
                <LogOut className="w-5 h-5 text-[var(--text-secondary)]" />
              </button>
            </>
          )}
        </div>
      </div>
    </header>
  );
};
